// app/layout.jsx
import "./globals.css";
import { futura, coveredByGrace } from "./fonts";
import ReduxProvider from "@/redux/reduxProvider";

export const metadata = {
  title: "Hair Saloon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${futura.variable} ${coveredByGrace.variable}`}>
      <body className="antialiased">
         <ReduxProvider>
        {children}
        </ReduxProvider></body>
    </html>
  );
}
